title = "mantou's blog"
theme = "LoveIt-0.3.0"
baseURL = "https://mantou-blog.pages.dev/"
languageCode = "zh-cn"
hasCJKLanguage = true

googleAnalytics = "G-0DGXTWGC32"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.home.profile]
  enable = true
  avatarURL = "/images/mantou.jpg"
  title = "mantou"
  subtitle = "变还是不变？这是个问题..."
  typeit = true
  social = true

[params.author]
  enable = true
  name = "mantou"
  avatar = "/images/mantou.jpg"
  link = "https://github.com/mantou"

[params.social]
  Email = "2114206091@qq.com"

  [params.social.x]
    weight = 3
    title = "X"
    url = "https://x.com/mantouaoao"

    [params.social.x.icon]
      Class = "fab fa-twitter fa-fw"

  [params.social.wechat]
    weight = 22
    title = "微信公众号"
    url = "https://weixin.sogou.com/weixin?type=1&query=mantou%20only"

    [params.social.wechat.icon]
      Src = "svg/icons/wechat-official.svg"

# ❌ 删除或注释掉这一行（GA4 不用这个）
# googleAnalytics = "G-0DGXTWGC32"

[params.analytics]
  enable = true

[params.analytics.google]
  id = "G-0DGXTWGC32"
  anonymizeIP = false


